//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18051
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KKBOX_News.Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KKBOX_News.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 關於 的當地語系化字串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 關於KKBOX 的當地語系化字串。
        /// </summary>
        public static string AboutKKBOX {
            get {
                return ResourceManager.GetString("AboutKKBOX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 關於KKBOX 音樂誌 的當地語系化字串。
        /// </summary>
        public static string AboutKKBOXNews {
            get {
                return ResourceManager.GetString("AboutKKBOXNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號 的當地語系化字串。
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳戶已存在 的當地語系化字串。
        /// </summary>
        public static string AccountExist {
            get {
                return ResourceManager.GetString("AccountExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號或密碼錯誤 的當地語系化字串。
        /// </summary>
        public static string AccountPasswordError {
            get {
                return ResourceManager.GetString("AccountPasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 行為 的當地語系化字串。
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 全選 的當地語系化字串。
        /// </summary>
        public static string AllSelect {
            get {
                return ResourceManager.GetString("AllSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 KKBOX 音樂誌 的當地語系化字串。
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 自動更新文章列表 的當地語系化字串。
        /// </summary>
        public static string AutoUpateArticleList {
            get {
                return ResourceManager.GetString("AutoUpateArticleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 自動更新 的當地語系化字串。
        /// </summary>
        public static string AutoUpdate {
            get {
                return ResourceManager.GetString("AutoUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 自動更新頻率 的當地語系化字串。
        /// </summary>
        public static string AutoUpdateFrequency {
            get {
                return ResourceManager.GetString("AutoUpdateFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 文章更新間隔 的當地語系化字串。
        /// </summary>
        public static string AutoUpdateInterval {
            get {
                return ResourceManager.GetString("AutoUpdateInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開啟自動更新 的當地語系化字串。
        /// </summary>
        public static string AutoUpdateOption {
            get {
                return ResourceManager.GetString("AutoUpdateOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確認密碼 的當地語系化字串。
        /// </summary>
        public static string CheckPassword {
            get {
                return ResourceManager.GetString("CheckPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 選擇封面 的當地語系化字串。
        /// </summary>
        public static string ChoosePhotoButton {
            get {
                return ResourceManager.GetString("ChoosePhotoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取消 的當地語系化字串。
        /// </summary>
        public static string ConcelButton {
            get {
                return ResourceManager.GetString("ConcelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確認 的當地語系化字串。
        /// </summary>
        public static string ConfrimButton {
            get {
                return ResourceManager.GetString("ConfrimButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 編輯 的當地語系化字串。
        /// </summary>
        public static string CoverEditSubTitle {
            get {
                return ResourceManager.GetString("CoverEditSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 封面資訊 的當地語系化字串。
        /// </summary>
        public static string CoverEditTitle {
            get {
                return ResourceManager.GetString("CoverEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 封面圖片 的當地語系化字串。
        /// </summary>
        public static string CoverImage {
            get {
                return ResourceManager.GetString("CoverImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除多個文章 的當地語系化字串。
        /// </summary>
        public static string DeleteAppbarMenu {
            get {
                return ResourceManager.GetString("DeleteAppbarMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除此目錄 的當地語系化字串。
        /// </summary>
        public static string DeleteDirectory {
            get {
                return ResourceManager.GetString("DeleteDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除 的當地語系化字串。
        /// </summary>
        public static string DeleteMenu {
            get {
                return ResourceManager.GetString("DeleteMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料夾名稱 的當地語系化字串。
        /// </summary>
        public static string DirectoryName {
            get {
                return ResourceManager.GetString("DirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 編輯封面資訊 的當地語系化字串。
        /// </summary>
        public static string EditCoverInfo {
            get {
                return ResourceManager.GetString("EditCoverInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 每隔 的當地語系化字串。
        /// </summary>
        public static string Every {
            get {
                return ResourceManager.GetString("Every", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 外部文章 的當地語系化字串。
        /// </summary>
        public static string ExternalArticleTitle {
            get {
                return ResourceManager.GetString("ExternalArticleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 內容 的當地語系化字串。
        /// </summary>
        public static string ExternalContent {
            get {
                return ResourceManager.GetString("ExternalContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 外部文章 的當地語系化字串。
        /// </summary>
        public static string ExternalDirTitle {
            get {
                return ResourceManager.GetString("ExternalDirTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 連結 的當地語系化字串。
        /// </summary>
        public static string ExternalLink {
            get {
                return ResourceManager.GetString("ExternalLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 標題 的當地語系化字串。
        /// </summary>
        public static string ExternalTitle {
            get {
                return ResourceManager.GetString("ExternalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用程式內直接顯示網頁 的當地語系化字串。
        /// </summary>
        public static string ExternalWebContent {
            get {
                return ResourceManager.GetString("ExternalWebContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 以外部瀏覽器開啟文章 的當地語系化字串。
        /// </summary>
        public static string ExternalWebOption {
            get {
                return ResourceManager.GetString("ExternalWebOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 個人精選 的當地語系化字串。
        /// </summary>
        public static string IntialDirTitle {
            get {
                return ResourceManager.GetString("IntialDirTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 加入我的精選 的當地語系化字串。
        /// </summary>
        public static string JoinMySelectAppbarMenu {
            get {
                return ResourceManager.GetString("JoinMySelectAppbarMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 加入我的精選 的當地語系化字串。
        /// </summary>
        public static string JoinMySelectMenu {
            get {
                return ResourceManager.GetString("JoinMySelectMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 加入我的精選 的當地語系化字串。
        /// </summary>
        public static string JoinMySelectTitle {
            get {
                return ResourceManager.GetString("JoinMySelectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 載入中... 的當地語系化字串。
        /// </summary>
        public static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登入 的當地語系化字串。
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登出帳號 的當地語系化字串。
        /// </summary>
        public static string LogoutAccout {
            get {
                return ResourceManager.GetString("LogoutAccout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 分 的當地語系化字串。
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更多文章及歌曲 的當地語系化字串。
        /// </summary>
        public static string more {
            get {
                return ResourceManager.GetString("more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 我的精選 的當地語系化字串。
        /// </summary>
        public static string MySelectedTitle {
            get {
                return ResourceManager.GetString("MySelectedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新資料夾 的當地語系化字串。
        /// </summary>
        public static string NewDirectory {
            get {
                return ResourceManager.GetString("NewDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增外部文章 的當地語系化字串。
        /// </summary>
        public static string NewExternalArticleButton {
            get {
                return ResourceManager.GetString("NewExternalArticleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼 的當地語系化字串。
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼與確認密碼不符 的當地語系化字串。
        /// </summary>
        public static string PWNotEqual {
            get {
                return ResourceManager.GetString("PWNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 註冊 的當地語系化字串。
        /// </summary>
        public static string RegistrationButton {
            get {
                return ResourceManager.GetString("RegistrationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 註冊帳號 的當地語系化字串。
        /// </summary>
        public static string RegistrationTitle {
            get {
                return ResourceManager.GetString("RegistrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 記住帳號密碼 的當地語系化字串。
        /// </summary>
        public static string RememberAccoutPW {
            get {
                return ResourceManager.GetString("RememberAccoutPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 LeftToRight 的當地語系化字串。
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 zh-tw 的當地語系化字串。
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 範例執行階段屬性值 的當地語系化字串。
        /// </summary>
        public static string SampleProperty {
            get {
                return ResourceManager.GetString("SampleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 搜尋儲存文章 的當地語系化字串。
        /// </summary>
        public static string SearchArticleButton {
            get {
                return ResourceManager.GetString("SearchArticleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 搜尋文章 的當地語系化字串。
        /// </summary>
        public static string SearchArticleTitle {
            get {
                return ResourceManager.GetString("SearchArticleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 搜尋 的當地語系化字串。
        /// </summary>
        public static string SearchButton {
            get {
                return ResourceManager.GetString("SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設定 的當地語系化字串。
        /// </summary>
        public static string SettingTitle {
            get {
                return ResourceManager.GetString("SettingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統 的當地語系化字串。
        /// </summary>
        public static string System {
            get {
                return ResourceManager.GetString("System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 訂閱中心 的當地語系化字串。
        /// </summary>
        public static string TopicsTitle {
            get {
                return ResourceManager.GetString("TopicsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 設定每次自動更新的頻率 的當地語系化字串。
        /// </summary>
        public static string UpdateIntervalContent {
            get {
                return ResourceManager.GetString("UpdateIntervalContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新中... 的當地語系化字串。
        /// </summary>
        public static string UpdateText {
            get {
                return ResourceManager.GetString("UpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 版本 的當地語系化字串。
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
